version: '2'

services:

  db_app:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  restfullapp:
    build: ./app
    env_file:
      - .env
    command: bash -c "python main.py"
    volumes:
      - ./app/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_app

volumes:
  postgres_data:
